### ISSUE TITLE
The backprop_e seems not correct

### ISSUE THREAD

**Issue by wilsoncao** [ajratner/patent-similarity#1]

**Comment by ajratner** [comment]
Hi Wilson,

This code was actually for a class project at MIT some time ago, and we
never fully tested it, beyond basic stuff.  It's quite possible there's an
error- my apologies!

I do noticed that you closed the issue- did you find anything?

-Alex

**Comment by wilsoncao** [comment]
Hi Alex,

The bug is acutually my mistakes when I implement the encoding function. And now I find that the code work just fine.
I find that in Socher's paper, there is a hidden layer in the autoencoder, but I didn't find any clue in your code. Does it work well without the hidden layer?

Finally, just for curiosity, can I know what your project is about?

Yours,
Wilson

------------------ 原始邮件 ------------------
发件人: "Alex Ratner";notifications@github.com;
发送时间: 2014年5月15日(星期四) 凌晨3:00
收件人: "ajratner/patent-similarity"patent-similarity@noreply.github.com; 
抄送: "275239608"275239608@qq.com; 
主题: Re: [patent-similarity] The backprop_e seems not correct (#1)

Hi Wilson, 

 This code was actually for a class project at MIT some time ago, and we 
 never fully tested it, beyond basic stuff.  It's quite possible there's an 
 error- my apologies! 

 I do noticed that you closed the issue- did you find anything? 

 -Alex

**Comment by ajratner** [comment]
Hey Wilson,

We implemented without the hidden layer to start and then never went beyond
that.

The goal of the project- done as part of the 6.864 class at MIT- was to
compute automatically how similar two patents were, however this proved to
be an ambitious task and we never managed to get the model to train in
reasonable time.  Then unfortunately we put the project on hold- hopefully
will get back to it eventually though!

If I may ask, what's your interest / background in this?

Hope alls well,
Alex

On Wednesday, May 14, 2014, WilsonCao notifications@github.com wrote:

> Hi Alex,
> 
> The bug is acutually my mistakes when I implement the encoding function.
> And now I find that the code work just fine.
> I find that in Socher's paper, there is a hidden layer in the autoencoder,
> but I didn't find any clue in your code. Does it work well without the
> hidden layer?
> 
> Finally, just for curiosity, can I know what your project is about?
> 
> Yours,
> Wilson
> 
> ------------------ 原始邮件 ------------------
> 发件人: "Alex Ratner";<notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>;
> 
> 发送时间: 2014年5月15日(星期四) 凌晨3:00
> 收件人: "ajratner/patent-similarity"<patent-similarity@noreply.github.com<javascript:_e(%7B%7D,'cvml','patent-similarity@noreply.github.com');>>;
> 
> 抄送: "275239608"<275239608@qq.com<javascript:_e(%7B%7D,'cvml','275239608@qq.com');>>;
> 
> 主题: Re: [patent-similarity] The backprop_e seems not correct (#1)
> 
> Hi Wilson,
> 
> This code was actually for a class project at MIT some time ago, and we
> never fully tested it, beyond basic stuff. It's quite possible there's an
> error- my apologies!
> 
> I do noticed that you closed the issue- did you find anything?
> 
> -Alex
> 
> On Wed, May 14, 2014 at 6:57 AM, WilsonCao <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > I reimplement the code in matlab and use gradient check to check the
> > gradient, I find that the gradW_e and gradb_e is not correct. Is there
> > anything wrong in the backprop_e function?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ajratner/patent-similarity/issues/1>
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ajratner/patent-similarity/issues/1#issuecomment-43164202
> .

## 

Sent from Gmail Mobile

**Comment by wilsoncao** [comment]
Hi Alex,

My interest is to improve the recursive autoencoder so that encoding and decoding layers can represent more words than before.

Is your patents dataset too large?  I am not sure what your dataset is, so I just guess. With the original dataset(MSRP) , training the encoding layers and decoding layers should cost about 5 hours. 

I haven't have a full test on my Matlab code, so I still not sure the performance of the algorithm.
If there is anything I can help, let me know and I will see what I can do.

Best,
Wilson 

------------------ 原始邮件 ------------------
发件人: "Alex Ratner";notifications@github.com;
发送时间: 2014年5月15日(星期四) 晚上11:13
收件人: "ajratner/patent-similarity"patent-similarity@noreply.github.com; 
抄送: "275239608"275239608@qq.com; 
主题: Re: [patent-similarity] The backprop_e seems not correct (#1)

Hey Wilson, 

 We implemented without the hidden layer to start and then never went beyond 
 that. 

 The goal of the project- done as part of the 6.864 class at MIT- was to 
 compute automatically how similar two patents were, however this proved to 
 be an ambitious task and we never managed to get the model to train in 
 reasonable time.  Then unfortunately we put the project on hold- hopefully 
 will get back to it eventually though! 

 If I may ask, what's your interest / background in this? 

 Hope alls well, 
 Alex 

 On Wednesday, May 14, 2014, WilsonCao notifications@github.com wrote: 

> Hi Alex, 
> 
> The bug is acutually my mistakes when I implement the encoding function. 
> And now I find that the code work just fine. 
> I find that in Socher's paper, there is a hidden layer in the autoencoder, 
> but I didn't find any clue in your code. Does it work well without the 
> hidden layer? 
> 
> Finally, just for curiosity, can I know what your project is about? 
> 
> Yours, 
> Wilson 
> 
> ------------------ 原始邮件 ------------------ 
> 发件人: "Alex Ratner";<notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>; 
> 
> 发送时间: 2014年5月15日(星期四) 凌晨3:00 
> 收件人: "ajratner/patent-similarity"<patent-similarity@noreply.github.com<javascript:_e(%7B%7D,'cvml','patent-similarity@noreply.github.com');>>; 
> 
> 抄送: "275239608"<275239608@qq.com<javascript:_e(%7B%7D,'cvml','275239608@qq.com');>>; 
> 
> 主题: Re: [patent-similarity] The backprop_e seems not correct (#1) 
> 
> Hi Wilson, 
> 
> This code was actually for a class project at MIT some time ago, and we 
> never fully tested it, beyond basic stuff. It's quite possible there's an 
> error- my apologies! 
> 
> I do noticed that you closed the issue- did you find anything? 
> 
> -Alex 
> 
> On Wed, May 14, 2014 at 6:57 AM, WilsonCao <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> 
> wrote: 
> 
> > I reimplement the code in matlab and use gradient check to check the 
> > gradient, I find that the gradW_e and gradb_e is not correct. Is there 
> > anything wrong in the backprop_e function? 
> > 
> > — 
> > Reply to this email directly or view it on GitHub< 
> > https://github.com/ajratner/patent-similarity/issues/1> 
> > . 
> > 
> > — 
> > Reply to this email directly or view it on GitHub. 
> 
> — 
> Reply to this email directly or view it on GitHubhttps://github.com/ajratner/patent-similarity/issues/1#issuecomment-43164202 
> . 

 --  
 Sent from Gmail Mobile

**Comment by ajratner** [comment]
Awesome!  Sounds very cool.  I'll be starting my PhD at Stanford next year
so would love especially to talk more then.  Best of luck on your project
in the mean time

-Alex
